[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/",
"forge-std/=lib/forge-std/src/",
"ds-test/=lib/ds-test/src/"]
fuzz_runs = 1000

# See more config options https://github.com/gakonst/foundry/tree/master/config